### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by huxiaoyi520** [BryanWang0702/MiSleep#1]
您好，我使用了pip install misleep 然后python -m运行。但是，出现各种报错，所以您能给出requirements.txt的相关内容吗？不胜感谢！

**Comment by BryanWang0702** [comment]
Hi，这是requirements.txt，你可以试试看。
[requirements.txt](https://github.com/user-attachments/files/15865997/requirements.txt)

另外，你运行的时候进入了你安装misleep的文件夹了吗？如果是使用miniconda的话，一般是要进入到`PATH_TO_MINICONDA/miniconda3/envs/ENV_NAME/Lib/site-packages` 这个路径。比如：
![图片](https://github.com/BryanWang0702/MiSleep/assets/78582816/bfc815f2-6d04-4653-8770-0590aa34b1be)

或者你可以`pip install misleep`之后，直接下载整个misleep项目到本地，然后进入这个文件夹，使用python -m运行。

如果还有问题，可以把报错信息贴出来，我们一起看看。

**Comment by huxiaoyi520** [comment]
感谢您的指导，我已经安装成功了。请问能否提供一些实例数据呢？因为好像一些电生理的数据是pl2或者其他的一些格式，但是您这个好像是matlab的数据格式。  不胜感激！

**Comment by huxiaoyi520** [comment]
非常感谢您的回复，我的邮箱是492545176@qq.com。感谢您百忙之中能给予指导！
